### ISSUE TITLE
test: mocked external data services

### ISSUE THREAD

**Issue by vanhoofmaarten** [isaaceindhoven/dependency-health-monitor#35]
Currently, we're using real-time data in our tests. This means that our test assertions might receive different results over time and that tests are prone to break without the source code having to be altered.

https://github.com/isaaceindhoven/dependency-health-monitor/blob/f8f38409e599c64a53e802892d4c4050e55d0f7d/packages/financial-health-calculator/tests/calculator/sustainability.spec.ts#L12

Can we to mock the responses from the API-calls?

**Comment by Ensar025** [comment]
An example where the API calls are mocked is the [GitHub scraper tests](https://github.com/isaaceindhoven/dependency-health-monitor/blob/master/packages/financial-health-calculator/tests/scrapers/github/github.spec.ts#L7).

**Comment by vanhoofmaarten** [comment]
Thank you for your explanation. Clear. Closing issue.
